### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xero12369** [radioactivetobi/geo-recon#3]
I ran the tool today, which i've used many times with success but today I got this:

[*] Geo-IP Lookup Complete!!!

[*] Running Reputation Check Against  

Traceback (most recent call last):
  File "/usr/share/geo-recon/geo-recon.py", line 69, in <module>
    check(syA1)                                                              
  File "/usr/share/geo-recon/modules/checkIp.py", line 26, in check          
    print ( Fore.WHITE + "Domain: " + json.dumps(decodedResponse ["data"]["domain"]))                                                                     
KeyError: 'data'       

any help would be appreciated

**Comment by Kadaber** [comment]
Same error here.

**Comment by radioactivetobi** [comment]
Thanks for bringing this issue to my attention, I'll have it resolved ASAP.

**Comment by tremcer** [comment]
Same error for me

**Comment by FabianPastor** [comment]
#4 Maybe this pull request can help somehow.
The error shows up because the API Key for abuseipdb has exceeded the limit of 1000 requests.
If you want to fix it by yourself you have to create an account on abuseipdb, generate your api key and edit they key that is stored on modules/checkIp.py

Maybe the owner of this repo should think on not shipping their own api key and forcing users that want to run this script to use their own key.

**Comment by NickCeylan** [comment]
> #4 Maybe this pull request can help somehow. The error shows up because the API Key for abuseipdb has exceeded the limit of 1000 requests. If you want to fix it by yourself you have to create an account on abuseipdb, generate your api key and edit they key that is stored on modules/checkIp.py
>
> Maybe the owner of this repo should think on not shipping their own api key and forcing users that want to run this script to use their own key.

Worked perfect, thnx
